<?php

namespace Lazer\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-03 at 00:26:34.
 */
class DatabaseTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Database
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Database;
    }

    /**
     * @expectedException Lazer\Classes\LazerException
     * @expectedExceptionMessageRegExp #Table "[a-zA-Z0-9_-]+" does not exists#
     */
    public function testTableNotExists()
    {
        $this->object->table('notExistingTable');
    }

}
