name: Unit

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php-version }}

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.2'
          - '7.4'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, json
          tools: phpunit:8

      - run: composer install --no-interaction --prefer-dist

      - name: PHPUnit
        run: phpunit --coverage-text